spring:
  config:
    activate:
      on-profile: local
  application:
    name: commerce-api
  datasource:
      master:
        hikari:
          username: root
          password: root
          driver-class-name: org.mariadb.jdbc.Driver
          url: jdbc:mariadb://localhost:3306/commerce
      slave:
        hikari:
          username: root
          password: root
          driver-class-name: org.mariadb.jdbc.Driver
          url: jdbc:mariadb://localhost:3307/commerce
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: "info"
    org.springframework.web: "debug"
    org.hibernate: "error"
server:
  port: 8081