spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: commerce
      username: developia
      password:
      authentication-database: admin
  application:
    name: commerce-api
  redis:
    host: localhost
    port: 6379
  datasource:
      master:
        hikari:
          username: root
          password: password
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://localhost:3306/commerce
      slave:
        hikari:
          username: root
          password: password
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://localhost:3306/commerce
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: "info"
    org.springframework.web: "debug"
    org.hibernate: "error"
server:
  port: 8081
